language: go

os:
  - linux
  - osx

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  global:
    GO111MODULE=on

before_install:
  - if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then go get github.com/axw/gocov/gocov github.com/mattn/goveralls; fi

script:
  - go test -v -tags ci ./...
  - if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then $GOPATH/bin/goveralls -service=travis-ci -ignore="examples/singlebar/single.go,examples/multibar/multi.go"; fi

notifications:
  email:
    on_success: change
    on_failure: always
